# Generated by Django 6.1 on 2026-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукция",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status_publication",
            field=models.BooleanField(default=False),
        ),
    ]
